<?php

namespace Europa\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    
    public function find($id)
    {
        return $this->getEntityManager()->createQuery
        ('
          SELECT a FROM EuropaBlogBundle:Author a 
          WHERE a.id = :id 
        ')
        ->setParameters(array('id' => $id))
        ->getOneOrNullResult();
    }
    
}
